modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
    modId="fuelgoeshere" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Fuel Goes Here" #mandatory
    credits="me" #optional
    authors="LobsterJonn" #optional
    description='''
Fuel should go to the fuel slot even when there's a smelting recipe for it.
'''
[[dependencies.fuelgoeshere]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.fuelgoeshere]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
